spring:
  application:
    name: module-apiCloudGateway
  cloud:
    gateway:
      routes:
        - id: security
          uri: lb://module-security
          predicates:
            - Path=/v2/sign**
        - id: adminuser
          uri: lb://module-user
          predicates:
            - Path=/v2/admin/users/**
            - Path=!/v2/admin/users/intra/**
          filters:
            - name: JwtFilter
        - id: user
          uri: lb://module-user
          predicates:
            - Path=/v2/users/**
            - Path=!/v2/users/intra/**
          filters:
            - name: JwtFilter
        - id: game
          uri: lb://module-main
          predicates:
            - Path=/v1/games**
            - Path=!/v1/games/intra/**
        - id: community
          uri: lb://module-community
          predicates:
            - Path=/v2/community**
            - Path=!/v2/community/intra/**
          filters:
            - name: JwtFilter

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

server:
  port: 9000

jwt:
  secret:
    key: NDkxOWJkYzRmNTU3N2RjMGMyZDFlZmM5NDMxODk3ZTUxYjdkZDNkOGZmNzU2YTJiMmQ0ZmNlNzVmYzE1MTRhZA==